apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-kw3p
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0068-tenant/tkrw-pr712-0075-0068-app/devfile-sample-kw3p@sha256:67a7c75b8f5c6cf13a01d5e8e3d47f3455560a0141eed8d202de6435df1a3df3
        name: my-nodejs
        resources: {}
status: {}
